language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - .pnpm-store

# S: Build Lifecycle
install:
  - npm install --global pnpm@11.7.0
  - pnpm install --frozen-lockfile --store-dir .pnpm-store

stages:
  - name: deploy

jobs:
  include:
    - stage: deploy
      script:
        - pnpm lint
        - pnpm test
        - pnpm run build
      deploy:
        edge: true
        provider: npm
        email: "marksz@teamsz.xyz"
        api_key: "${NPM_TOKEN}"
        skip_cleanup: true
        on:
          branch: master
branches:
  only:
    - master
